server:
  port: 6868
eureka:
                     client:
                       #注册到eureka no
                       register-with-eureka: false
                       #拿到注册信息 no
                       fetch-registry: false
                       service-url:
                         #Eureka客户端与Eureka服务端进行交互的地址
                         defaultZone: http://127.0.0.1:${server.port}/eureka/